---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: user-quota
  namespace: dev
spec:
  scopeSelector:
    matchExpressions:
      - scopeName: PriorityClass
        operator: In
        values: ["usermgmt-user-priority"]
  hard:
    requests.cpu: "1000m"
    requests.memory: "512Mi"
    limits.cpu: "2000m"
    limits.memory: "1024Mi"
    pods: "5"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: admin-quota
  namespace: dev
spec:
  scopeSelector:
    matchExpressions:
      - scopeName: PriorityClass
        operator: In
        values: ["usermgmt-admin-priority"]
  hard:
    requests.cpu: "250m"
    requests.memory: "64Mi"
    limits.cpu: "500m"
    limits.memory: "128Mi"
    pods: "1"
