---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-mysql-pv-claim
  namespace: database
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 1Gi
