---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: usermgmt-admin-sa
  namespace: usermgm
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: usermgmt-user-sa
  namespace: usermgm
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-sa
  namespace: database
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: usermgmt-role
  namespace: usermgm
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: usermgmt-rolebinding
  namespace: usermgm
subjects:
- kind: ServiceAccount
  name: usermgmt-admin-sa
  namespace: usermgm
- kind: ServiceAccount
  name: usermgmt-user-sa
  namespace: usermgm
roleRef:
  kind: Role
  name: usermgmt-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-dns-resolver
rules:
- apiGroups: [""]
  resources: ["services", "endpoints", "pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-dns-resolver-binding
subjects:
- kind: ServiceAccount
  name: usermgmt-admin-sa
  namespace: usermgm
- kind: ServiceAccount
  name: usermgmt-user-sa
  namespace: usermgm
roleRef:
  kind: ClusterRole
  name: pod-dns-resolver
  apiGroup: rbac.authorization.k8s.io
