---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: usermgmt-admin-sa
  namespace: usermgm
  labels:
    app.kubernetes.io/instance: usermgm
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: usermgmt-user-sa
  namespace: usermgm
  labels:
    app.kubernetes.io/instance: usermgm
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-sa
  namespace: database
  labels:
    app.kubernetes.io/instance: usermgm
---
# Role for accessing metrics in usermgm namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-metrics-reader
  namespace: usermgm
  labels:
    app.kubernetes.io/instance: usermgm
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods"]
  verbs: ["get", "list"]
---
# Role for accessing MySQL in database namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mysql-access
  namespace: database
  labels:
    app.kubernetes.io/instance: usermgm
rules:
- apiGroups: [""]
  resources: ["services", "endpoints", "pods"]
  verbs: ["get", "list", "watch"]
---
# RoleBinding for metrics in usermgm namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-metrics-reader-binding
  namespace: usermgm
  labels:
    app.kubernetes.io/instance: usermgm
subjects:
- kind: ServiceAccount
  name: usermgmt-admin-sa
  namespace: usermgm
- kind: ServiceAccount
  name: usermgmt-user-sa
  namespace: usermgm
roleRef:
  kind: Role
  name: pod-metrics-reader
  apiGroup: rbac.authorization.k8s.io
---
# RoleBinding for MySQL access in database namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mysql-access-binding
  namespace: database
  labels:
    app.kubernetes.io/instance: usermgm
subjects:
- kind: ServiceAccount
  name: usermgmt-admin-sa
  namespace: usermgm
- kind: ServiceAccount
  name: usermgmt-user-sa
  namespace: usermgm
roleRef:
  kind: Role
  name: mysql-access
  apiGroup: rbac.authorization.k8s.io
