apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: database
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: db
  strategy:
    type: Recreate 
  template: 
    metadata: 
      labels: 
        app: db
    spec: 
      containers:
        - name: db
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: example
            - name: MYSQL_DATABASE
              value: pythonlogin
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
            - name: usermanagement-dbcreation-script
              mountPath: /docker-entrypoint-initdb.d
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          livenessProbe:
            exec:
              command: [ "mysqladmin", "ping", "-u", "root", "-pexample" ]
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            exec:
              command: [ "mysqladmin", "ping", "-u", "root", "-pexample" ]
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
      volumes: 
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: nfs-mysql-pv-claim
        - name: usermanagement-dbcreation-script
          configMap:
            name: usermanagement-dbcreation-script
