---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: user-quota
  namespace: staging
spec:
  scopeSelector:
    matchExpressions:
      - scopeName: PriorityClass
        operator: In
        values: ["usermgmt-user-priority"]
  hard:
    requests.cpu: "2500m"
    requests.memory: "640Mi"
    limits.cpu: "5000m"
    limits.memory: "1280Mi"
    pods: "10"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: admin-quota
  namespace: staging
spec:
  scopeSelector:
    matchExpressions:
      - scopeName: PriorityClass
        operator: In
        values: ["usermgmt-admin-priority"]
  hard:
    requests.cpu: "500m"
    requests.memory: "128Mi"
    limits.cpu: "1000m"
    limits.memory: "256Mi"
    pods: "2"
