---
apiVersion: v1
kind: Namespace
metadata:
  name: app
  labels:
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: usermgmt-user-priority
value: 1000
globalDefault: false
description: "Higher priority for user-facing workloads."
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: usermgmt-admin-priority
value: 500
globalDefault: false
description: "Lower priority for admin workloads."
