---
apiVersion: v1
kind: Namespace
metadata:
  name: usermgm
  labels:
    name: usermgm
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: database
  labels:
    name: database
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota-database
  namespace: database
spec:
  hard:
    requests.cpu: "1000m"
    requests.memory: "2048Mi"
    limits.cpu: "2000m"
    limits.memory: "4Gi"
    pods: "4"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: usermgmt-user-quota
  namespace: usermgm
spec:
  scopeSelector:
    matchExpressions:
      - scopeName: PriorityClass
        operator: In
        values:
          - usermgmt-user-priority
  hard:
    requests.cpu: "2500m"
    requests.memory: "640Mi"
    limits.cpu: "5000m"
    limits.memory: "1280Mi"
    pods: "10"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: usermgmt-admin-quota
  namespace: usermgm
spec:
  scopeSelector:
    matchExpressions:
      - scopeName: PriorityClass
        operator: In
        values:
          - usermgmt-admin-priority
  hard:
    requests.cpu: "500m"
    requests.memory: "128Mi"
    limits.cpu: "1000m"
    limits.memory: "256Mi"
    pods: "2"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: usermgmt-user-priority
value: 1000
globalDefault: false
description: "Higher priority for user-facing workloads."
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: usermgmt-admin-priority
value: 500
globalDefault: false
description: "Lower priority for admin workloads."
