---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: usermgmt-admin-sa
  namespace: app
  labels:
    app.kubernetes.io/instance: usermgm
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: usermgmt-user-sa
  namespace: app
  labels:
    app.kubernetes.io/instance: usermgm
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-sa
  namespace: app
  labels:
    app.kubernetes.io/instance: usermgm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-metrics-reader
  namespace: app
  labels:
    app.kubernetes.io/instance: usermgm
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mysql-access
  namespace: app
  labels:
    app.kubernetes.io/instance: usermgm
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-metrics-reader-binding
  namespace: app
  labels:
    app.kubernetes.io/instance: usermgm
subjects:
  - kind: ServiceAccount
    name: usermgmt-admin-sa
    namespace: app
  - kind: ServiceAccount
    name: usermgmt-user-sa
    namespace: app
roleRef:
  kind: Role
  name: pod-metrics-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mysql-access-binding
  namespace: app
  labels:
    app.kubernetes.io/instance: usermgm
subjects:
  - kind: ServiceAccount
    name: usermgmt-admin-sa
    namespace: app
  - kind: ServiceAccount
    name: usermgmt-user-sa
    namespace: app
roleRef:
  kind: Role
  name: mysql-access
  apiGroup: rbac.authorization.k8s.io
