---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-namespaces-resourcesq.yaml
  - 01-storage-class.yaml
  - 02-rbac-and-sa.yaml
  - 03-mysql-configMap.yaml
  - 04-mysql-statefulset.yaml
  - 05-mysql-clusterip-service.yaml
  - 06-UserMgmtAdmin-Deployment.yaml
  - 07-UserMgmtAdmin-Service.yaml
  - 08-UserMgmtUser-Deployment.yaml
  - 09-UserMgmtUser-Service.yaml
  - 10-networkpolicy-for-db.yaml
  - 11-hpa-config.yaml

images:
  - name: lroquec/usermgm-admin
    newName: lroquec/usermgm-admin
    newTag: base
  - name: lroquec/usermgm-user
    newName: lroquec/usermgm-user
    newTag: base

namePrefix: base-

commonLabels:
  app.kubernetes.io/part-of: user-management
  app.kubernetes.io/managed-by: kustomize
